# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-10 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0002_auto_20190710_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(1, 'Menswear'), (2, 'Womenswear'), (3, 'Generalised')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='photos/'),
        ),
    ]
