# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-10 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0003_auto_20190710_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='optional_screenshot',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='screenshot',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sitename',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='technologies',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
