# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-10 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0004_auto_20190710_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='optional_screenshot',
        ),
        migrations.RemoveField(
            model_name='product',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sitename',
        ),
        migrations.RemoveField(
            model_name='product',
            name='technologies',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(1, 'Menswear'), (2, 'Womenswear'), (3, 'Generalised')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
