# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-10 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0005_auto_20190710_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(1, '1'), (2, '1'), (3, '3')], max_length=50),
        ),
    ]
