# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-10 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0007_auto_20190710_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Menswear', 'Menswear'), ('womenswear', 'womenswear'), ('Generalised', 'Generalised')], max_length=50),
        ),
    ]
