# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-12 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0011_auto_20190712_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='your_fashion_taste',
            field=models.CharField(choices=[('Rocker looks', 'Rocker looks'), ('Tomboy Fashion', 'Tomboy Fashion'), ('Sophisticated Fashion', 'Sophisticated Fashion'), ('Artsy Fashion', 'Artsy Fashion'), ('Casual Fashion', 'Casual Fashion'), ('Vintage Fashion', 'Vintage Fashion')], default='No style', max_length=100),
        ),
    ]
