# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-26 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0012_profile_your_fashion_taste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
