# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-28 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0015_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='heading',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
