# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-01 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0019_auto_20191001_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bursary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=40)),
                ('Last_name', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(default='0726xxxxxx', max_length=10, null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=100, null=True)),
                ('Have_you_participated_in_any_aid_providing_programmes_before', models.CharField(choices=[('Yes', 'Yes'), ('No', 'NO')], max_length=100, null=True)),
                ('Whcih_avenue_was_most_influential_in_your_learning', models.CharField(choices=[('Books', 'Books'), ('Newspapers', 'Newspapers'), ('Magazines', 'Magazines'), ('E-Learning', 'E-Learning'), ('Online Articles', 'Online Articles'), ('Journals', 'Journals'), ('Teachers', 'Teachers'), ('Other', 'Other')], max_length=100, null=True)),
                ('What_is_your_average_family_monthly_income', models.CharField(choices=[('Above 60,000 ksh', 'Above 60,000 ksh'), ('40,000 - 50,000 ksh', '40,000 - 50,000 ksh'), ('20,000 - 40,000 ksh', '20,000 - 40,000 ksh'), ('1,000 - 20,000 ksh', '1,000 - 20,000 ksh'), ('Below 1,000 ksh', 'Below 1,000 ksh')], max_length=100, null=True)),
                ('What_is_your_highest_level_of_education_completed', models.CharField(choices=[('High-School', 'High-School'), ('Diploma', 'Diploma'), ('Bachelor-Degree', 'Bachelor-Degree'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate'), ('Other', 'Other')], max_length=100, null=True)),
                ('Please_outline_any_community_work_you_have_undertaken', models.TextField(max_length=2000)),
            ],
        ),
    ]
