# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-02 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0020_bursary'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend.Event')),
                ('plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend.Future_plans')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend.Project')),
            ],
        ),
        migrations.RenameField(
            model_name='bursary',
            old_name='Whcih_avenue_was_most_influential_in_your_learning',
            new_name='Which_avenue_was_most_influential_in_your_learning',
        ),
        migrations.RemoveField(
            model_name='bursary',
            name='Have_you_participated_in_any_aid_providing_programmes_before',
        ),
        migrations.AddField(
            model_name='bursary',
            name='Have_you_participated_in_any_aid_providing_programme_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bursary',
            name='What_is_your_highest_level_of_education_completed',
            field=models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('Primary School', 'Primary School'), ('High School', 'High School'), ('Diploma', 'Diploma'), ('Bachelor Degree', 'Bachelor Degree'), ('Masters Degree', 'Masters Degree'), ('Doctorate', 'Doctorate'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
