# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-02 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0023_news_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='events',
        ),
        migrations.RemoveField(
            model_name='news',
            name='plans',
        ),
        migrations.RemoveField(
            model_name='news',
            name='projects',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='photos/'),
        ),
    ]
